In [1]:
# Import banknote authentication loading function
from frbcs_xai.data.loader import load_uci_dataset

df, y = load_uci_dataset(267)

# The first three examples
df.head(3)

   variance  skewness  curtosis  entropy
0    3.6216    8.6661   -2.8073 -0.44699
1    4.5459    8.1674   -2.4586 -1.46210
2    3.8660   -2.6383    1.9242  0.10645

In [2]:
import pandas as pd

# Number of missing values per variable
missing_count = df.isna().sum()

# Percentage of missing values
missing_pct = df.isna().mean() * 100

missing_summary = pd.DataFrame({
    "Missing Count": missing_count,
    "Missing (%)": missing_pct
})

print(missing_summary)

          Missing Count  Missing (%)
variance              0          0.0
skewness              0          0.0
curtosis              0          0.0
entropy               0          0.0

In [6]:
# Number of missing values for target variable
missing_count_y = y.isna().sum()

# Percentage of missing values
missing_pct_y = y.isna().mean() * 100

missing_summary_y = pd.DataFrame({
    "Missing Count": missing_count_y,
    "Missing (%)": missing_pct_y
})

print(missing_summary_y)

       Missing Count  Missing (%)
class              0          0.0

In [8]:
import numpy as np
import pandas as pd

# Get the class categories and the number of example per class
classes, counts = np.unique(y, return_counts=True)

class_distribution = pd.DataFrame({
    "Class": classes,
    "Count": counts,
    "Percentage (%)": counts / counts.sum() * 100
})

display(class_distribution)

   Class  Count  Percentage (%)
0      0    762       55.539359
1      1    610       44.460641